flags: {}
packages:
  - '.'
extra-deps: []
extra-package-dbs:
    - ../lib2/.stack-work/install/x86_64-linux/lts-12.7/8.4.3/pkgdb/
    - ../lib1/.stack-work/install/x86_64-linux/lts-12.7/8.4.3/pkgdb/
resolver: lts-12.7
